### ISSUE TITLE
tclkit with own extension fails with missing symbol Tcl_GetObjResult

### ISSUE THREAD

**Issue by ikrabbe** [patthoyts/kitgen#10]
I tried to build starkit, that includes an own extension. When I link then extension and load into my tclsh, everything works fine, but when I run the loader through the generated kits I get undefined symbols.

The moduletest.tcl is 

    load cardcheck/lib/filter_module.so creditcardfilter
    package require creditcardfilter 1.0
    puts {gogogo...}
    puts "filter result = [filter you suck123bla]"
    puts {done.}
    pkg_mkIndex cardcheck/lib

The `pkg_mkIndex` writes the `pkgIndex.tcl` to wrap into the starkit, later.

Running the kit gives

    ./cardcheck.kit
    couldn't load file "/tmp/tcl_hyzjuc": /tmp/tcl_hyzjuc: undefined symbol: Tcl_GetObjResult
        while executing
    "load /home/ingo/src/tcltk/cardcheck.kit/lib/filter_module.so"
        ("package ifneeded creditcardfilter 1.0" script)
        invoked from within
    "package require creditcardfilter"
        (file "/home/ingo/src/tcltk/cardcheck.kit/lib/app-cardcheck/cardcheck.tcl" line 3)
        invoked from within
    "source /home/ingo/src/tcltk/cardcheck.kit/lib/app-cardcheck/cardcheck.tcl"
        ("package ifneeded app-cardcheck 1.0" script)
        invoked from within
    "package require app-cardcheck 1.0"
        (file "/home/ingo/src/tcltk/cardcheck.kit/main.tcl" line 3)

Same with `/home/couldn't load file "cardcheck/lib/filter_module.so":

    couldn't load file "cardcheck/lib/filter_module.so": cardcheck/lib/filter_module.so: undefined symbol: Tcl_GetObjResult
        while executing
    "load cardcheck/lib/filter_module.so creditcardfilter"
        (file "moduletest.tcl" line 1)

Running the tcl8.5 system tclsh works fine: `tclsh moduletest.tcl`

    gogogo...
    anaylze bytes 0-10
    filter result = 3
    done.

**Comment by ikrabbe** [comment]
BTW.: I tried to link against the tcl8.6.a static library, which might produce the problem. I'm just unsure right now, where to use shared libraries and where I can use static libraries.

**Comment by bgstech** [comment]
Modify your extension to use Tcl stubs, basically by switching from `Tcl_PkgRequire()` to `Tcl_InitStubs()`.  See the how-to on the [Developer Xchange](http://www.tcl.tk/doc/howto/stubs.html).  Then link your extension against the stub library. e.g.

    gcc -shared -o libThing.so thing.o foo.o bar.o \
        -L/path/to/kitgen/lib -ltclstub8.5 ...

**Comment by ikrabbe** [comment]
Thanks for the hint! I already did `Tcl_InitStubs()`, but I did not linked against libtclstub.

If I follow the "Developer Xchange" and link against libtclstub **instead** of libtcl I get a missing tclStubPtr. If I link against both the kit crashes with a segmentain fault.

I will try to debug this further down, later.

**Comment by ikrabbe** [comment]
This works, finally! Thank you for the hint.
